import {
  erc20sData,
  zeroAddress,
} from "@defi.org/web3-candies";

import Linea from "assets/linea.svg";
export const networks = {
  eth: {
    id: 1,
    name: "Ethereum",
    shortname: "eth",
    native: {
      address: zeroAddress,
      symbol: "ETH",
      decimals: 18,
      logoUrl: "https://app.1inch.io/assets/images/network-logos/ethereum.svg",
    },
    wToken: erc20sData.eth.WETH,
    publicRpcUrl: "https://eth.llamarpc.com",
    logoUrl: "https://app.1inch.io/assets/images/network-logos/ethereum.svg",
    explorer: "https://etherscan.io",
  },
  bsc: {
    id: 56,
    name: "Bsc",
    shortname: "bsc",
    native: {
      address: zeroAddress,
      symbol: "BNB",
      decimals: 18,
      logoUrl: "https://app.1inch.io/assets/images/network-logos/bsc_2.svg",
    },
    wToken: erc20sData.bsc.WBNB,
    publicRpcUrl: "https://bsc-dataseed.binance.org",
    logoUrl: "https://app.1inch.io/assets/images/network-logos/bsc_2.svg",
    explorer: "https://bscscan.com",
    eip1559: false,
  },
  poly: {
    id: 137,
    name: "Polygon",
    shortname: "poly",
    native: {
      address: zeroAddress,
      symbol: "MATIC",
      decimals: 18,
      logoUrl: "https://app.1inch.io/assets/images/network-logos/polygon.svg",
    },
    wToken: erc20sData.poly.WMATIC,
    publicRpcUrl: "https://polygon-rpc.com",
    logoUrl: "https://s2.coinmarketcap.com/static/img/coins/128x128/3890.png",
    explorer: "https://polygonscan.com",
    eip1559: true,
  },
  arb: {
    id: 42161,
    name: "Arbitrum",
    shortname: "arb",
    native: {
      address: zeroAddress,
      symbol: "ETH",
      decimals: 18,
      logoUrl: "https://app.1inch.io/assets/images/network-logos/ethereum.svg",
    },
    wToken: erc20sData.arb.WETH,
    publicRpcUrl: "https://arb1.arbitrum.io/rpc",
    logoUrl: "https://app.1inch.io/assets/images/network-logos/arbitrum.svg",
    explorer: "https://arbiscan.io",
    eip1559: true,
  },
  ftm: {
    id: 250,
    name: "Fantom",
    shortname: "ftm",
    native: {
      address: zeroAddress,
      symbol: "FTM",
      decimals: 18,
      logoUrl: "https://app.1inch.io/assets/images/network-logos/fantom.svg",
    },
    wToken: erc20sData.ftm.WFTM,
    publicRpcUrl: "https://rpc.ftm.tools",
    logoUrl: "https://app.1inch.io/assets/images/network-logos/fantom.svg",
    explorer: "https://ftmscan.com",
    eip1559: true,
  },
  base: {
    id: 8453,
    name: "Base",
    shortname: "base",
    native: {
      address: zeroAddress,
      symbol: "ETH",
      decimals: 18,
      logoUrl: "https://app.1inch.io/assets/images/network-logos/ethereum.svg",
    },
    wToken: erc20sData.base.WETH,
    publicRpcUrl: "https://mainnet.base.org",
    logoUrl: "https://app.1inch.io/assets/images/network-logos/base.svg",
    explorer: "https://basescan.org",
    eip1559: false,
  },
  linea: {
    id: 59144,
    name: "Linea",
    shortname: "linea",
    native: {
      address: zeroAddress,
      symbol: "ETH",
      decimals: 18,
      logoUrl: "https://app.1inch.io/assets/images/network-logos/ethereum.svg",
    },
    wToken: erc20sData.linea.WETH,
    publicRpcUrl: "https://rpc.linea.build",
    logoUrl: Linea,
    explorer: "https://lineascan.build",
    eip1559: false,
  },
  sei: {
    id: 1329,
    name: "Sei",
    shortname: "sei",
    native: {
      address: zeroAddress,
      symbol: "SEI",
      decimals: 18,
      logoUrl:
        "https://raw.githubusercontent.com/dragonswap-app/assets/main/logos/0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE/logo.png",
    },
    wToken: {
      symbol: "WSEI",
      address: "0xE30feDd158A2e3b13e9badaeABaFc5516e95e8C7",
      decimals: 18,
      weth: false,
      logoUrl:
        "https://raw.githubusercontent.com/dragonswap-app/assets/main/logos/0xE30feDd158A2e3b13e9badaeABaFc5516e95e8C7/logo.png",
    },
    publicRpcUrl: "https://evm-rpc.sei-apis.com",
    logoUrl: "https://s2.coinmarketcap.com/static/img/coins/128x128/23149.png",
    explorer: "https://seitrace.com",
    eip1559: false,
  },
  blast: {
    id: 81457,
    name: "Blast",
    shortname: "blast",
    native: {
      address: zeroAddress,
      symbol: "BLAST",
      decimals: 18,
      logoUrl:
        "https://raw.githubusercontent.com/dragonswap-app/assets/main/logos/0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE/logo.png",
    },
    wToken: {
      symbol: "WSEI",
      address: "0xE30feDd158A2e3b13e9badaeABaFc5516e95e8C7",
      decimals: 18,
      weth: false,
      logoUrl:
        "https://raw.githubusercontent.com/dragonswap-app/assets/main/logos/0xE30feDd158A2e3b13e9badaeABaFc5516e95e8C7/logo.png",
    },
    publicRpcUrl: "https://evm-rpc.sei-apis.com",
    logoUrl: "https://s2.coinmarketcap.com/static/img/coins/128x128/28480.png",
    explorer: "https://blastscan.io",
    eip1559: false,
  },
  avax: {
    id: 43114,
    name: "Avalanche",
    shortname: "avax",
    native: {
      address: "0x0000000000000000000000000000000000000000",
      symbol: "AVAX",
      decimals: 18,
      logoUrl: "https://app.1inch.io/assets/images/network-logos/avalanche.svg",
    },
    wToken: {
      symbol: "WAVAX",
      address: "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7",
      decimals: 18,
      weth: true,
      logoUrl:
        "https://tokens-data.1inch.io/images/0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7.png",
    },
    publicRpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    logoUrl: "https://app.1inch.io/assets/images/network-logos/avalanche.svg",
    explorer: "https://snowtrace.io",
    baseGasPrice: 0,
    eip1559: true,
    pendingBlocks: true,
  },
};
