import { Configs } from "@orbs-network/twap-sdk";
import { networks } from "./networks";
import { Partner } from "./types";



export const PARTNERS: Partner[] = [
  {
    id: "swapx",
    website: "https://swapx.fi",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/34753.png",
    name: "SwapX",
    twapId: Configs?.SwapX.partner,
    liquidityHubChains: [networks.sonic.id],
  },
  {
    id: "quickswap",
    website: "https://quickswap.exchange/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/19966.png",
    name: "Quickswap",
    twapId: Configs?.QuickSwap.partner,
    liquidityHubChains: [networks.poly.id, networks.eth.id],
  },
  {
    id: "spookyswap",
    website: "https://spooky.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/1455.png",
    name: "Spookyswap",
    twapId: Configs?.SpookySwap.partner,
    liquidityHubChains: [networks.ftm.id, networks.sonic.id],
  },
  {
    id: "lynex",
    website: "https://www.lynex.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/7957.png",
    name: "Lynex",
    twapId: Configs?.Lynex.partner,
    liquidityHubChains: [networks.linea.id],
  },
  {
    id: "thena",
    website: "https://thena.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/5803.png",
    name: "Thena",
    twapId: Configs?.Thena.partner,
    liquidityHubChains: [networks.bsc.id],
  },
  {
    id: "arbidex",
    website: "https://arbidex.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/6506.png",
    name: "Arbidex",
    twapId: Configs?.Arbidex.partner,
    liquidityHubChains: [networks.arb.id],
  },
  {
    id: "chronos",
    website: "https://chronos.exchange/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/24158.png",
    name: "Chronos",
    twapId: Configs?.Chronos.partner,
    liquidityHubChains: [],
  },
  {
    id: "baseswap",
    website: "https://baseswap.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/27764.png",
    name: "Baseswap",
    twapId: Configs?.BaseSwap.partner,
    liquidityHubChains: [],
  },
  {
    id: "pancakeswap",
    website: "https://baseswap.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/7186.png",
    name: "PancakeSwap",
    twapId: Configs?.PancakeSwap.partner,
    liquidityHubChains: [],
  },
  {
    id: "sushiswap",
    website: "https://www.sushi.com",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/6758.png",
    name: "SushiSwap",
    twapId: Configs?.SushiBase.partner,
    liquidityHubChains: [],
  },
  {
    id: "dragonswap",
    website: "https://dragonswap.app",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/10363.png",
    name: "DragonSwap",
    twapId: Configs?.DragonSwap.partner,
    liquidityHubChains: [networks.sei.id],
  },
  {
    id: "retro",
    website: "https://retro.finance/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/7516.png",
    name: "Retro",
    twapId: Configs?.Retro.partner,
    liquidityHubChains: [],
  },
  {
    id: "fenix",
    website: "https://fenix.finance/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/7516.png",
    name: "Fenix",
    twapId: '',
    liquidityHubChains: [networks.blast.id],
  },
  {
    id: "teafi",
    website: "https://app.tea-fi.com/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/33924.png",
    name: "Teafi",
    twapId: Configs?.TeaFi.partner,
    liquidityHubChains: [],
  },
  {
    id: "sparkdex",
    website: "https://sparkdex.ai/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/36569.png",
    name: "SparkDEX",
    twapId: Configs?.SparkDEX.partner,
    liquidityHubChains: [],
  },
  {
    id: "ramses",
    website: "https://ramses.exchange/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/23858.png",
    name: "Ramses",
    twapId: Configs?.Ramses.partner,
    liquidityHubChains: [],
  },
];


